[package]
name = "korean-transliteration-py"
version.workspace = true
edition = "2021"
license.workspace = true

[lib]
name = "korean_transliteration"
crate-type = ["cdylib", "rlib"]
test = false
doctest = false

[features]
default = []
extension-module = ["pyo3/extension-module"]

[dependencies]
korean-transliteration.workspace = true
pyo3.workspace = true
