[package]
name = "korean-transliteration"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "korean_transliteration"

[dependencies]
sosap = { git = "https://github.com/seanghay/sosap.git", rev = "90cbd8d" }
once_cell.workspace = true
thiserror.workspace = true
anyhow.workspace = true
flate2 = { version = "1.0", default-features = false, features = ["rust_backend"] }
